/*
 * CERAMIC_HEATER_CFG.h
 *
 *  Created on: Feb 6, 2026
 *      Author: Moata
 */

#ifndef ECU_LAYER_CERAMIC_HEATER_ECU_CERAMIC_HEATER_CFG_H_
#define ECU_LAYER_CERAMIC_HEATER_ECU_CERAMIC_HEATER_CFG_H_



#endif /* ECU_LAYER_CERAMIC_HEATER_ECU_CERAMIC_HEATER_CFG_H_ */
