/*
 * COOLER_(PELTIER)_CFG.h
 *
 *  Created on: Feb 6, 2026
 *      Author: Moata
 */

#ifndef ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_CFG_H_
#define ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_CFG_H_



#endif /* ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_CFG_H_ */
