/*
 * COOLER_(PELTIER).h
 *
 *  Created on: Feb 6, 2026
 *      Author: Moata
 */

#ifndef ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_H_
#define ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_H_



#endif /* ECU_LAYER_COOLER_PELTIER_ECU_COOLER_PELTIER_H_ */
